### ISSUE TITLE
Add to JSPM registry

### ISSUE THREAD

**Issue by geelen** [geelen/plugin-postcss#1]
Pinging @guybedford on this one. Because this isn't usable directly, but can be used to create loaders really easily, should this go in the JSPM registry? Or just live on NPM?

**Comment by guybedford** [comment]
I'm really liking where this project is going. Certainly we can include it in the registry.

I was wondering if we can make it a direct plugin instead of a plugin creator.

Perhaps by having load metadata specify the set of transforms to run:

``` javascript
System.meta['some/file.css!'] = {
  postCSS: [
    {
      transform: 'postcss-import', // this is the module name of the transform
      options: {}
    }//, ...
  ]
};
```

This way when we introduce wildcard config (coming soon honest), we can then have package specify their own post-css transforms in the package.json!

Or am I taking this too far?

**Comment by geelen** [comment]
Can you explain more about the wildcard config? Is it just to not have to configure the `meta` for each file that's used? So you could do `System.meta['*.css'] = {` and ensure every CSS file was loaded with the right chain of processors (without needing the `!` at the end as well?)

**Comment by geelen** [comment]
Oh and by the way, this project, used without any plugins, is effectively doing precisely what `plugin-css` is doing, except with the addition of livereload. Should the two be combined? Personally I think autoprefixer should be included by default. It's not often you want to _not_ use autoprefixer. And for a lot of projects, autoprefixer + live-reload would be plenty to get started with.

**Comment by geelen** [comment]
One more thing, we could forget about customisable plugins & just ship a pack of predefined ones. In fact, we could make a `plugin-cssnext` based off https://github.com/cssnext/cssnext. In that way it's like JSPM is a way to use future JS & CSS syntax together. I might convert TypeSlab to cssnext syntax and see if I like it. Previously I've preferred SCSS-style, but maybe it's time for that to change.

**Comment by guybedford** [comment]
Yes that's exactly what the wildcard config does, and it layers as well so you can have any number of levels of wildcards applying to a module.

I'm loving the vision of a future JS & CSS combo workflow! I'll happily review to see if we can get to a point where this is the default CSS plugin. Note the two practical concerns here are checking where we are on browser support and CSS line-by-line debugging in the inspector as well.

Also it could be worth having the `fetch` in this plugin just a fetch, and then have the processing in the `translate` hook, and injection in the `instantiate` hook to make the pipeline transparent / hookable.

**Comment by geelen** [comment]
Superseded by https://github.com/geelen/jspm-loader-css/issues/3
