### ISSUE TITLE
Another "in the wild" example

### ISSUE THREAD

**Issue by MadLittleMods** [geelen/plugin-postcss#2]
I noticed a project linked at the bottom of the readme as an in the wild example.

I have been using `plugin-postcss` and it has been working great [here](https://github.com/MadLittleMods/postcss-css-variables/blob/master/playground/css.js). The plugin is used to process styles for this [code playground for a PostCSS plugin](https://madlittlemods.github.io/postcss-css-variables/playground/).

Just thought I would give you a heads-up.

**Comment by geelen** [comment]
Awesome! I'll add a link!
