### ISSUE TITLE
Specify `processor.process` -> `opts.from`

### ISSUE THREAD

**Issue by MadLittleMods** [geelen/plugin-postcss#4]
[`processor.process(css, opts)`](https://github.com/postcss/postcss/blob/master/docs/api.md#processorprocesscss-opts) takes an `opts` object and it can be useful to specify the `from` path for import resolves.

Also from the docs:

> `from`: the path of the CSS source file. You should always set from, because it is used in source map generation and syntax error messages.

**Comment by geelen** [comment]
As this plugin has been superseded by https://github.com/geelen/jspm-loader-css, I'm not sure if this issue still applies? If so, let's raise an issue & discuss there?
